# Generated by Django 4.2 on 2023-04-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='question',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='pollchoice',
            name='value',
            field=models.CharField(max_length=256),
        ),
    ]
