# Generated by Django 4.2 on 2023-04-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_poll_question_alter_pollchoice_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='expire_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
