# Generated by Django 4.2 on 2023-04-22 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_poll_expire_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='time',
            new_name='duration',
        ),
    ]
