# Generated by Django 4.2 on 2023-04-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_rename_time_poll_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='expire_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
